using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace NightSignal.Core.Meet
{
    /// <summary>
    /// The soundtrack manifest (authored/music.cues.json, regenerated by the audio tool): each cue's display title,
    /// category and full length (intro + loop body). The room server runs the shared boombox from these numbers without
    /// the synthesizer; clients read the same titles.
    /// </summary>
    public sealed class MusicCues
    {
        public sealed class Cue
        {
            public string Id = "", Title = "", Category = "";
            public double Seconds;
        }

        readonly Dictionary<string, Cue> cues = new Dictionary<string, Cue>();

        public IEnumerable<Cue> All => cues.Values;

        public static MusicCues Parse(string json)
        {
            var m = new MusicCues();
            if (string.IsNullOrEmpty(json)) return m;
            foreach (JToken c in JObject.Parse(json)["cues"] ?? new JArray())
            {
                string id = (string)c["id"];
                if (string.IsNullOrEmpty(id)) continue;
                m.cues[id] = new Cue
                {
                    Id = id,
                    Title = (string)c["displayTitle"] ?? (string)c["title"] ?? id,
                    Category = (string)c["category"] ?? "",
                    Seconds = (double?)c["loopEndSeconds"] ?? 0.0,
                };
            }
            return m;
        }

        /// <summary>Full length in seconds (0 for an unknown cue: the boombox refuses it).</summary>
        public double Seconds(string id) => id != null && cues.TryGetValue(id, out Cue c) ? c.Seconds : 0.0;

        public string Title(string id) => id != null && cues.TryGetValue(id, out Cue c) ? c.Title : id;

        public bool Has(string id) => id != null && cues.ContainsKey(id);
    }
}
