using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using NightSignal.Content;
using NightSignal.Core.Content;
using NightSignal.Track;
using NightSignal.Track.Generation;
using UnityEditor;
using UnityEngine;

namespace NightSignal.Editor.ContentTools
{
    /// <summary>
    /// The §14 course-uniqueness report (<see cref="CourseUniqueness"/>) on the real generated centrelines of every counted
    /// course: Evidence/courses/uniqueness-report.txt. Flags any course under 70% exclusive for a visual review.
    /// </summary>
    public static class CourseUniquenessReport
    {
        [MenuItem("Night Signal/Content/Course Uniqueness Report")]
        public static string Run()
        {
            ContentCatalogue cat = ContentLibrary.Load().Catalogue;
            var lines = new Dictionary<string, IReadOnlyList<(double X, double Z)>>();
            var kinds = new Dictionary<string, string>();
            foreach (CourseDef c in cat.Courses.Where(c => CourseUniqueness.Counted(c.Kind)))
            {
                string path = RouteIO.RoutePath(c.Id);
                if (!File.Exists(path)) continue;
                string json = File.ReadAllText(path);
                TrackData t = CourseGenerator.BuildTrackData(RouteIO.Parse(json), RouteIO.SourceHash(json));
                var pts = new List<(double, double)>();
                for (float d = 0f; d <= t.LengthMetres; d += (float)CourseUniqueness.SampleMetres)
                {
                    Vector3 p = t.SampleAt(d).Position;
                    pts.Add((p.x, p.z));
                }
                lines[c.Id] = pts;
                kinds[c.Id] = c.Kind;
            }
            List<CourseUniquenessRow> rows = CourseUniqueness.Evaluate(lines);
            var sb = new StringBuilder();
            sb.AppendLine("# Course uniqueness (spec §14): the share of each counted course's centreline farther than 8 m from every other counted course,");
            sb.AppendLine("# in the frame each course is authored in (its own scene, starting at its grid); the first and last 100 m are the allowed");
            sb.AppendLine($"# approaches. Required: {CourseUniqueness.Required:P0}. Generated by Night Signal > Content > Course Uniqueness Report from the routes.");
            sb.AppendLine("course  kind      length m  exclusive  closest  shared  verdict");
            foreach (CourseUniquenessRow r in rows.OrderBy(r => r.Exclusive))
                sb.AppendLine($"{r.CourseId,-6}  {kinds[r.CourseId],-8}  {r.LengthMetres,8:F0}  {r.Exclusive,9:P1}  {r.ClosestCourse,-7}  {r.SharedWithClosest,6:P1}  {(r.Passes ? "pass" : "FLAG — review")}");
            int flagged = rows.Count(r => !r.Passes);
            sb.AppendLine($"# {rows.Count} counted courses; {flagged} flagged; lowest {rows.Min(r => r.Exclusive):P1} ({rows.OrderBy(r => r.Exclusive).First().CourseId}).");
            Directory.CreateDirectory("Evidence/courses");
            File.WriteAllText("Evidence/courses/uniqueness-report.txt", sb.ToString());
            string summary = $"{rows.Count} counted courses, {flagged} flagged, lowest {rows.Min(r => r.Exclusive):P1}";
            Debug.Log("[NightSignal.Content] uniqueness: " + summary);
            return summary;
        }
    }
}
